TemperaturePrediction/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', user_views.login_user, name="login"),
    path('admin/', admin.site.urls),
    path('historicalTemp/', include('HistoricalTemp.urls')),
    path('predictedTemp/', include('PredictedTemp.urls')),
    path('currentTemp/', include('currentTemp.urls')),
    path('register/', user_views.register_user, name='register'),
    path('profile/',user_views.profile_user, name="profile"),
    path('login/', user_views.login_user, name="login"),
    url(r'^comment_app/', include('comment_app.urls')),
    path('weather/', include('weather.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment_app/urls.py
from django.conf.urls import url
from . import views

app_name = "comment_app"


urlpatterns = [
	url(r'^$',views.list_of_post, name='list_of_post'),
	url(r'^(?P<slug>[-\w]+)/$',views.post_detail, name='post_detail'),
	url(r'^category/(?P<category_slug>[-\w]+)/$',views.list_of_post_by_category, name='list_of_post_by_category'),	
	url(r'^(?P<slug>[-\w]+)/comment/$',views.add_comment, name='add_comment')


]

weather/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('delete/<city_name>/', views.delete_city, name='delete_city'),
]

comment_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.




class Category(models.Model):
	name = models.CharField(max_length = 250)
	slug = models.SlugField(max_length = 250,unique  = True)



	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def get_absolute_url(self):
		return reverse('comment_app:list_of_post_by_category',args = [self.slug])



	def __str__(self):
		return self.name


class Post(models.Model):
	STATUS_CHOICES = (
		('draft','Draft'),
		('published','Published'),
	)
	category = models.ForeignKey('Category',on_delete = models.CASCADE,) 
	title = models.CharField(max_length = 250)
	slug = models.SlugField(max_length = 250,unique = True)
	content = models.TextField()
	seo_title = models.CharField(max_length = 250)
	seo_description = models.CharField(max_length = 250)
	author = models.ForeignKey(User,on_delete= models.PROTECT,related_name = 'blog_posts')
	published = models.DateTimeField(default = timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=9,choices = STATUS_CHOICES,default = 'draft')



	def get_absolute_url(self):
		return reverse('comment_app:post_detail',args = [self.slug])


	def __str__(self):
		return self.title

#---------------------------------------------------------------------------------------comment wala part

class Comment(models.Model):
	post = models.ForeignKey('Post', related_name = 'comments',on_delete = models.CASCADE,)
	user = models.CharField(max_length = 250)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add = True)
	approved = models.BooleanField(default = False)



	def approved(self):
		self.approved = True
		self.save()


	def __str__(self):
		return self.user

comment_app/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields  = ('user','email','body')
		

comment_app/views.py
from django.shortcuts import render, get_object_or_404 , redirect
from .models import Post, Category


from .forms import CommentForm
# Create your views here.

from django.contrib.auth.decorators import login_required

@login_required(login_url="/login/")
def list_of_post_by_category(request,category_slug):
	categories  = Category.objects.all()
	post = Post.objects.filter(status = 'published')
	if category_slug:
		category = get_object_or_404(Category , slug = category_slug)
		post = post.filter(category = category)
	template = 'comment_app/category/list_of_post_by_category.html'
	context = {'categories': categories, 'post':post,'category':category}
	return render(request,template,context)


@login_required(login_url="/login/")
def list_of_post(request):
	post = Post.objects.filter(status = 'published')
	template = 'comment_app/post/list_of_post.html'
	context = {'post':post}
	return render(request,template,context)
@login_required(login_url="/login/")
def post_detail(request,slug):
	post = get_object_or_404(Post,slug = slug)
	template = 'comment_app/post/post_detail.html'
	context = {'post':post}
	return render(request,template, context)
#--------------------------------------------------------------------------------------------------
@login_required(login_url="/login/")
def add_comment(request,slug):
	post = get_object_or_404(Post,slug = slug)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit = False)
			comment.post = post
			comment.save()
			return redirect('comment_app:post_detail',slug = post.slug)
	else:
		form = CommentForm()
	template = 'comment_app/post/add_comment.html'
	context = {'form':form}
	return render(request,template, context)

comment_app/templates/comment_app/post/add_comment.html
{% extends 'comment_app/base.html'%}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style>
		body,html{
			height: 100%;
			margin:0;
		}
		.abcd{
			background-image: url({% static "weather1.jpg" %});
			height: 100%;
			background-position: center;
			background-repeat: no-repeat;
			background-size: cover;

		}
	</style>
</head>
<body class="abcd">
	<h1>Add New Comment</h1>
	<form method="POST">{% csrf_token %}
	{{form|crispy}}
	<button type="submit">Submit</button>
	</form>
{% endblock %}
</body>
</html>

comment_app/templates/comment_app/post/list_of_post.html
{% extends 'comment_app/base.html'%}
{% load static %}


{% block description %}This is description{% endblock %}

{% block title %}List of blogs post{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style>
	body,html{
		height: 100%;
		margin:0;
	}
	.abc{
		background-image: url({% static "weather1.jpg" %});
		height: 100%;
		background-position: center;
		background-repeat: no-repeat;
		background-size: cover;

	}
	
</style>
</head>
<body class="abc" >
<div class="row">
	<div class="col-md-8">
	<div  class="page-header" >
		<h1>{{post.title}}</h1>
	</div>		
	{% for posts in post %}
		<h2 ><a href="{{posts.get_absolute_url}}" style="color: black;">{{posts.title}}</a></h2>
		<small>Written by - {{posts.author}} on {{posts.published}} in <a href="{{posts.category.get_absolute_url}}">{{posts.category}}</a></small> 
		<hr>
		{{post.content|truncatewords:40|linebreaks}}
	{% endfor %}
	</div>
</div>
{% endblock %}

</body>
</html>

comment_app/templates/comment_app/post/post_detail.html
{% extends 'comment_app/base.html'%}
{% load static %}

{% block description %}{{post.seo_description}}{% endblock %}
{% block title %}{{post.seo_title}}{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style>
	body,html{
		height: 100%;
		margin:0;
	}
	.ab{
		background-image: url({% static "weather1.jpg" %});
		height: 100%;
		background-position: center;
		background-repeat: no-repeat;
		background-size: cover;

	}
</style>
<body class="ab">
<div class="row">
	<div class="col-md-8">
		<div class="page-header">
		<h1>{{post.title}}</h1>
		</div>	
		<small>Written by - {{post.author}} on {{post.published}} in <a href="{{post.category.get_absolute_url}}">{{post.category}}</a></small> 
		{{post.content|linebreaks}}
		<div class="page-header">
		<h2>Leave a Comment<small style="color: black"> &nbsp;&nbsp;&nbsp;&nbsp; Total number of comments {{post.comments.count}}</small></h1>
		</div>
		<p class="text-center"><button type="button" class="btn-btn-default"><a href="{% url 'comment_app:add_comment' slug=post.slug %}">Leave A Comment</a></button></p>
		{% for comment in post.comments.all %}
		<div class="panel panel-default">
			<div class="panel-heading">{{ comment.user}} commented on {{ comment.created}}</div>
			
			<div class="panel-body">{{ comment.body}}</div>
	
		</div>
		{% empty %}
		<p>There is no comments</p>
		{% endfor %}
	</div>
</div>
{% endblock %}
</body>
</html>